# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: afb4945c1263ee2f08052a462c77e98fe40f43ca33c2590ef9545010ac76825eadc210717ab3d09e2854269c244942cc4d109e456bada54ca0f9f493748cf4b7

test:
  secret_key_base: 1441ee3e17068b4409793d3b92f5eb0a4278dd93b5965d615a8aa0af0a83131674beadf5cf089c8ce5b88f3900ffa1eed80f56993a2c97fbc6199e4e9d8cc267

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
